name: main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Rebot server
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.PRIVATE_KEY}}
        port: 22
        script:
          reboot

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.PRIVATE_KEY}}
        port: 22
        script: |
          cd ~
          cd test_bot
          cd testAiogramBot
          git pull origin master
          git status
          source ~/test_bot/test_bot_env/bin/activate
          python3 aiogram_run.py
          deactivate

