name: main
on: [push]
jobs:
  New-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run venv
        run: source test_bot/test_bot_env/bin/activate

      - name: Run
        run: python3 aiogram_run.py

